### PR TITLE
Implemented fix for display of Recaptcha

### PR DESCRIPTION
**Pull request by anuragji**

### CODE REVIEW

**Comment by zerocrates** [comment]
It looks like what happened here is that the problem was temporarily fixed, but the fix was applied directly to the CSS, not the SASS source, so the next change to the SASS ended up overriding the intended fix back to being broken (incidentally, this PR makes that same mistake).

We'll go back and re-apply the original intended fix.

**Comment by anuragji** [comment]
Sounds good!

**Comment by zerocrates** [comment]
Okay, the problem should have been fixed (again) by 8119f5ecc17e911221dcc826fc415607ee1b31a4

Let us know if it's working after an updated pull.

**Comment by anuragji** [comment]
Yep, that works... Thanks - I'll close the p.r.

**Pull request closed without merging**
